# Generated by Django 3.0.6 on 2020-05-31 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='azimuth',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='center_distance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='metro_distance',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price_metr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price_total',
            field=models.FloatField(null=True),
        ),
    ]
