# Generated by Django 3.0.6 on 2020-05-31 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200531_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='real_price_metr',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='real_price_total',
        ),
    ]
