# Generated by Django 3.0.6 on 2020-05-31 23:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200531_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='azimuth',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='predicted_price_metr',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flat',
            name='predicted_price_total',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
