# Generated by Django 3.0.6 on 2020-06-01 01:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200601_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='center_distance',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(20000)]),
        ),
    ]
